name: Run Build & Unit Tests
on:
  pull_request:
jobs:
  build:
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package.yml@e3e734b910af78371b2c9a1c6856446d17421f50'
    with:
      run_tests: true
