name: Run Build & Unit Tests
on:
  pull_request:
jobs:
  build:
    uses: 'flowfuse/github-actions-workflows/.github/workflows/build_node_package.yml@132a77418c21639c18318ed6a687e28caa7f4ce8'
    with:
      run_tests: true
