name: Build and publish packages to the registry
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: 'flowfuse/github-actions-workflows/.github/workflows/build_node_package.yml@132a77418c21639c18318ed6a687e28caa7f4ce8'
    with:
      run_tests: true
  
  publish:
    needs: build
    if: |
      github.ref == 'refs/heads/main'
    uses: 'flowfuse/github-actions-workflows/.github/workflows/publish_node_package.yml@132a77418c21639c18318ed6a687e28caa7f4ce8'
    with:
      package_name: node-red-dashboard
      publish_package: true
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}
