name: Build and publish packages to private registry
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: 'flowforge/github-actions-workflows/.github/workflows/build_node_package.yml@e3e734b910af78371b2c9a1c6856446d17421f50'
    with:
      run_tests: true
  
  publish:
    needs: build
    if: |
      github.ref == 'refs/heads/main'
    uses: 'flowforge/github-actions-workflows/.github/workflows/publish_node_package.yml@e3e734b910af78371b2c9a1c6856446d17421f50'
    with:
      package_name: node-red-dashboard
      publish_package: true
